[bundle]
identifier = "dev.harmeepatel"
publisher = "Harmee Patel"
copyright = "2026 Harmee Patel"
category = "Productivity"
short_description = "Invoice and Stock management for Achal Enterprise"
icon = ["assets/icon.ico"]

[application]
name = "AE"
default_platform = "desktop"
out_dir = "dist"
tailwind_input = "assets/css/main.css"
tailwind_output = "assets/css/tailwind.css"

[web.app]
# HTML title tag content
title = "AE"

# include `assets` in web platform
[web.resource]
# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]
# Javascript code file
# serve: [dev-server] only
script = []
