// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package page

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"ae_invoice/src/util"
	component "ae_invoice/src/web/components"
	layout "ae_invoice/src/web/layouts"
)

func tableHeader() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<tr><th>#</th><td>Serial #</td><td>Name</td><td>HSN</td><td>Quantity</td><td>Price ₹</td><td>Discount</td><th><button class=\"btn p-0 w-8 h-8 lg:w-12 lg:h-12\" disabled=\"disabled\"><img src=\"static/images/trash.svg\" class=\"w-4 h-4 lg:w-6 lg:h-6\"></button></th></tr>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var businessDetails = [2][]component.FieldConfig{
	{
		{Type: "text", Name: "name", PlaceHolder: "Rohit Patel", Legend: "Name"},
		{Type: "text", Name: "gstin", PlaceHolder: "24ABCPM1234L1Z5", Legend: "GSTIN"},
		{Type: "number", Name: "gst", PlaceHolder: "5.0", Legend: "GST"},
		{Type: "email", Name: "email", PlaceHolder: "abc@xyz.com", Legend: "Email (Optional)"},
		{Type: "tel", Name: "phone", PlaceHolder: "11111 99999", Legend: "Phone"},
		{Type: "text", Name: "remark", PlaceHolder: "XYZ Missing in this order", Legend: "Remark (Optional)"},
	},
	{
		{Type: "text", Name: "shopNo", PlaceHolder: "A123", Legend: "Shop No"},
		{Type: "text", Name: "line1", PlaceHolder: "Complex / Plaza", Legend: "Line 1"},
		{Type: "text", Name: "line2", PlaceHolder: "Landmark", Legend: "Line 2 (Optional)"},
		{Type: "text", Name: "line3", PlaceHolder: "Street Name", Legend: "Line 3 (Optional)"},
		{Type: "text", Name: "city", PlaceHolder: "Ahmedabad", Legend: "City"},
		{Type: "select", Name: "state", PlaceHolder: "Gujarat", Legend: "State"},
		{Type: "number", Name: "postalCode", PlaceHolder: "382424", Legend: "Postal Code"},
	},
}
var productDetails = [2][]component.FieldConfig{
	{
		{Type: "text", Name: "serialNumber", PlaceHolder: "A1B2C3", Legend: "Serial #"},
		{Type: "text", Name: "productName", PlaceHolder: "Bib Cock", Legend: "Name"},
		{Type: "text", Name: "hsn", PlaceHolder: "123456", Legend: "HSN"},
	},
	{
		{Type: "number", Name: "quantity", PlaceHolder: "4", Legend: "Quantity"},
		{Type: "number", Name: "sellPrice", PlaceHolder: "256", Legend: "Price ₹"},
		{Type: "number", Name: "discount", PlaceHolder: "5", Legend: "Discount"},
	},
}

func Index(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			if util.IsDev {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script>\n    function clearLocalStorage() {\n        console.log(\"localStorage cleared\")\n        localStorage.clear()\n    }\n</script>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " <span id=\"tmp\"></span><main role=\"main\" id=\"main\" class=\"max-w-7xl m-auto mb-4 px-4 2xl:px-0\"><div class=\"flex items-center justify-between sm:mb-4\"><h1 class=\"text-4xl\">Party Information</h1>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if util.IsDev {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<button class=\"btn btn-accent\" onclick=\"clearLocalStorage()\">clear local storage</button>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><section id=\"party-info\" class=\"w-full mb-12\"><form data-on:submit=\"@post('/invoice/submit', {contentType: 'form'})\" method=\"POST\"><div id=\"customer-info\" class=\"w-full mb-6 sm:mb-3 flex-col sm:flex-row flex gap-4\"><fieldset id=\"left\" class=\"w-full min-w-0\"><legend class=\"fieldset-legend font-light text-sm\">Business Details</legend> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, field := range businessDetails[0] {
				templ_7745c5c3_Err = component.Field(field).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</fieldset><fieldset id=\"right\" class=\"w-full min-w-0\"><legend class=\"fieldset-legend font-light text-sm\">Billing Address</legend> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, field := range businessDetails[1] {
				templ_7745c5c3_Err = component.Field(field).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</fieldset></div><fieldset id=\"product-info\" class=\"flex md:gap-2 flex-col md:flex-row\"><legend class=\"fieldset-legend font-light text-sm\">Product Details</legend><div class=\"flex gap-2\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, field := range productDetails[0] {
				templ_7745c5c3_Err = component.Field(field).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div><div class=\"flex gap-2\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, field := range productDetails[1] {
				templ_7745c5c3_Err = component.Field(field).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div></fieldset><div class=\"flex w-full gap-2 mt-4\"><button type=\"submit\" class=\"grow-8 btn btn-primary btn-lg text-xl disabled:cursor-not-allowed\" data-attr:disabled=\"!$hasError\" disabled>Generate Invoice</button> <button class=\"grow-2 btn btn-primary btn-lg brightness-200 disabled:cursor-not-allowed\" type=\"button\" data-on:click=\"@post('/product/add')\" data-target=\"#products-list\" data-swap=\"innerHTML\" data-attr:disabled=\"!$productHasError\" disabled><svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\" width=\"24px\" fill=\"#e3e3e3\"><path d=\"M440-120v-320H120v-80h320v-320h80v320h320v80H520v320h-80Z\"></path></svg></button></div></form></section><section id=\"product-list\" class=\"overflow-x-auto max-h-[640px] lg:max-h-[1024px]\"><table class=\"table table-pin-rows table-pin-cols text-balance\"><thead class=\"text-lg font-light\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = tableHeader().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</thead>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = component.ProductBody().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<tfoot class=\"text-lg font-light\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = tableHeader().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</tfoot></table></section></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base(title).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
